name: Build & tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: apt
      run: |
        curl -L https://packagecloud.io/varnishcache/varnish64/gpgkey | sudo apt-key add - &&
        echo "deb https://packagecloud.io/varnishcache/varnish64/ubuntu/ bionic main" | sudo tee /etc/apt/sources.list.d/varnish.list &&
        sudo apt-get update &&
        sudo apt-get install -y docutils-common varnish-dev
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
